### ISSUE TITLE
Crosswalk hygiene 

### ISSUE THREAD

**Issue by erika-tyagi** [uclalawcovid19behindbars/facility_data#2]
* Consolidate and clean state names per new conventions (e.g. DC and District of Columbia, update Abroad, Deleware and Delaware, etc.) 
* Update missing HIFLD and use this to populate other missing data 
* Update missing county data (Increasingly using this for viz) 
* Geocode missing lat/long data where address data is available

**Comment by mceverett8** [comment]
Fixed in new update and added in the missing HIFLD numbers. We probably need a broader strategy for geocoding and updating these sheets and maybe loop in the linkage volunteers.
