### ISSUE TITLE
Add missing federal facility names from latest scraped data

### ISSUE THREAD

**Issue by erika-tyagi** [uclalawcovid19behindbars/facility_data#25]
There are 103 rows where we're scraping BOP population data that aren't in the crosswalks: 
```
read_scrape_data() %>% 
    filter(is.na(Facility.ID)) %>% 
    filter(Jurisdiction == "federal") 
```

These are probably low-priority since we're scraping `Residents.Population`, but no COVID data for these.

**Comment by erika-tyagi** [comment]
This also relates to the federal vaccine data facility name issue. Basically, the approach we decide to go with for cases/deaths data and vaccine data aggregation (or lack of aggregation) should also be the approach for population data too. (cc: @nmmarquez, @hjohns12)

**Comment by hjohns12** [comment]
That makes sense to me!

**Comment by erika-tyagi** [comment]
done as best as can be for now w/ 61d2c8c (mapped 1:1s)
