### ISSUE TITLE
Add missing CA staff names from latest scraped data 

### ISSUE THREAD

**Issue by erika-tyagi** [uclalawcovid19behindbars/facility_data#26]
There are 25 rows where we're scraping CA staff data that aren't in the crosswalks: 
```
read_scrape_data() %>% 
    filter(is.na(Facility.ID)) %>% 
    filter(State == "California")
```
The names are scraped from [here](https://www.cdcr.ca.gov/covid19/cdcr-cchcs-covid-19-status/), and they're all county names - so it's not totally clear what they're referring to.

**Comment by hjohns12** [comment]
Noting that this is on hold until @mceverett8 gets more info on who is included in these staff counts (if he can)

**Comment by hjohns12** [comment]
Update: couldn't get ahold of CDCR / CCHCS, and until we do, the naming convention is as follows:

COUNTY NAME + "County Staff"

**Comment by hjohns12** [comment]
Integrated this here! https://github.com/uclalawcovid19behindbars/facility_data/commit/d0dddd32db5a1c40a886e8b2d76be9d7fe275359
