### ISSUE TITLE
Standardize CDCR CCHCS worksite location names

### ISSUE THREAD

**Issue by hjohns12** [uclalawcovid19behindbars/facility_data#42]
In both fac_data and fac_spellings, all facilities with “CDCR CCHCS worksite location” in the name should be standardized to one format

“X COUNTY WORKSITE LOCATION”

**Comment by erika-tyagi** [comment]
Just realized the email we got from Sharon today relates to this! 

Website says MENDOCINO COUNTY STAFF, which was mistaken for MENDOCINO COUNTY JAIL (rather than MENDOCINO COUNTY WORKSITE LOCATION).

**Comment by hjohns12** [comment]
It seems to me that we should change the xwalk_name_clean from what is currently "MENDOCINO COUNTY STAFF" to "CDCR CCHCS WORKSITE LOCATION MENDOCINO COUNTY".  Does that make sense to you?

I just checked, and the last time we had `Staff.Confirmed` data for CDCR CCHCS WORKSITE LOCATION MENDOCINO COUNTY was January 11, 2021. The value of `Staff.Confirmed` was 2 on 1/11/21, and it hasn't changed ([current source](http://104.131.72.50:3838/scraper_data/raw_files/2021-08-03_california_staff.html)).

I think it would be less likely that someone would mistake our Mendocino-located facility with Mendocino County Jail if we change the clean name to be CDCR CCHCS WORKSITE blah blah blah

**Comment by hjohns12** [comment]
PS, I wonder if this is a more global change that needs to happen with all facilities in CA called "EXAMPLE COUNTY STAFF"? Is this what your original question was getting at?! probably

Next step seems like: cross-check the last-collected value for `Staff.Confirmed` for a given "CDCR CCHCS WORKSITE LOCATION EXAMPLE COUNTY" facility against the first-collected `Staff.Confirmed` number for a given "EXAMPLE COUNTY STAFF" facility

**Comment by erika-tyagi** [comment]
> It seems to me that we should change the xwalk_name_clean from what is currently "MENDOCINO COUNTY STAFF" to "CDCR CCHCS WORKSITE LOCATION MENDOCINO COUNTY". Does that make sense to you?

Yup! Could we just change all of the California staff site names in one go and close out the issue?
