### ISSUE TITLE
Facility column values

### ISSUE THREAD

**Issue by nmmarquez** [uclalawcovid19behindbars/facility_data#5]
@mceverett8 It looks like in the updated Facility info in the facility column there are values called `Aged and Infirmed` as well as `Age and Infirmed`. Are these supposed to be separate or can we collapse them into one value?

**Comment by nmmarquez** [comment]
examples

https://github.com/uclalawcovid19behindbars/facility_data/blob/master/data_sheets/20.12.19_fac_info.csv#L20

https://github.com/uclalawcovid19behindbars/facility_data/blob/master/data_sheets/20.12.19_fac_info.csv#L1185

**Comment by mceverett8** [comment]
Fixed in new update and readme.
