### ISSUE TITLE
New Jersey youth facilities 

### ISSUE THREAD

**Issue by erika-tyagi** [uclalawcovid19behindbars/facility_data#58]
There are two facilities in New Jersey (reported by the DOC [here](https://www.state.nj.us/corrections/pages/COVID19Updates.shtml)) that I'm not sure should be treated as youth facilities: `GARDEN STATE YOUTH CORRECTIONAL FACILITY` and `WILLIAM H FAUVER YOUTH CORRECTIONAL FACILITY`. In both cases, they house individuals aged 18-30, which I think makes them less comparable to juvenile detention facilities in other states. 

Main concern I have is that treating them as `Web.Group = Juvenile` means we're undercounting COVID cases in adult prisons (i.e. reporting 3,900 instead of around 4,800) and making New Jersey's youth case count seem really high (i.e. 800+ cases among youth, when the next closest state has ~200). 

Thoughts on calling these adult facilities instead?

**Comment by hjohns12** [comment]
Good catch! It's bizarre to me that they're called "youth correctional facilities" when everyone is over the age of 18, and since that's the case, I think it's a good call to change `Age` to adult for these two. I can do this!

**Comment by hjohns12** [comment]
Pushed straight to main so closing this! https://github.com/uclalawcovid19behindbars/facility_data/commit/71aac03267ae41979e7441ec7e245ca172bc8845
