### ISSUE TITLE
Misclassified juvenile facilities 

### ISSUE THREAD

**Issue by erika-tyagi** [uclalawcovid19behindbars/facility_data#59]
Adding a couple more to the list of facilities that I think should be considered Adult, rather than Juvenile: 

* `PINE GROVE CORRECTIONAL INSTITUTION` in Pennsylvania (`1186`) - says [here](https://www.cor.pa.gov/Facilities/StatePrisons/Pages/Pine-Grove.aspx) that average age is 38 and 39% of population is under 20 
* `RACINE YOUTHFUL OFFENDER CORRECTIONAL FACILITY` in Wisconsin (`1695`) - says [here](https://doc.wi.gov/Pages/OffenderInformation/AdultInstitutions/RacineYouthfulOffenderCorrectionalFacility.aspx) that the facility houses people ages 18 through 24

**Comment by hjohns12** [comment]
Agreed with both!

**Comment by erika-tyagi** [comment]
Done [here](https://github.com/uclalawcovid19behindbars/facility_data/commit/4a07e54df2c16272967839f96be3a89ce35b18dd)!
