### ISSUE TITLE
MN population anchor to NA

### ISSUE THREAD

**Issue by hjohns12** [uclalawcovid19behindbars/facility_data#67]
- Add a line to [the script](https://github.com/uclalawcovid19behindbars/facility_data/blob/master/R/ad-hoc/update_anchors.R) that updates population anchors, turning the value for Minnesota's `Residents.Population` to NA with an informative comment about this change

_Originally posted by @hjohns12 in https://github.com/uclalawcovid19behindbars/covid19_behind_bars_scrapers/issues/346#issuecomment-999074225_

**Comment by mceverett8** [comment]
Think this is a duplicate issue to the other MN to NA issue just closed.
